id: P0697AF99
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4289
  instance_id: http://purl.bdrc.io/resource/IE1KG4289
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་ལུང་དོན་རྒྱ་མཚོ།
  alt_title:
    en-x-mixed:
    - Śer phyin gyi mdo daṅ mṅon rtogs rgyan gyi ʼgrel pa daṅ bcas paʼi lus daṅ yan
      lag rgyas pa bśad pa luṅ don rgya mtsho /mdzad pa po, Śākya-mchog-ldan Dri-med-legs-paʼi-blo-gros.
  author: http://purl.bdrc.io/resource/P396
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    9b6bff1570e64ced931d12a0ea08446e:
      title: པོད ༡་མངོན་རྟོགས་རྒྱན་གྱི་འགྲེལ་པ་ལུང་དོན་རྒྱ་མཚོ
      volume_number: 1
      base_file: UT1KG4289_I1PD98536_0000.txt
      reference: http://purl.bdrc.io/resource/VL8C41C6BB823DE0B4
      image_group: I1PD98536
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/MW1KG4289
  - http://purl.bdrc.io/resource/W1KG4289
  ocr_software: Namsel
created_at: '2021-12-22T10:40:28.041576'
last_modified_at: '2021-12-22T10:40:28.041583'
statistics:
  total_words: 60391
  total_non_words: 6064
quality:
  non_words_ratio: 0.1
